import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { motion, useScroll, useSpring } from 'framer-motion'
import { ArrowUpRight, ChevronRight, Cpu, Globe2, Mail, MapPin, Menu, Sparkles, Users, X, Zap } from 'lucide-react'
import './styles.css'
import './partners.css'

const events=[{day:'14',month:'OCT',title:'HCAI Leadership Lessons',type:'LEADERSHIP · TALK'},{day:'24',month:'OCT',title:'Innovation Xperience Kick-off',type:'COMMUNITY · TBA'},{day:'24—25',month:'NOV',title:'HCAI Symposium',type:'HUMAN-CENTRED AI'}]
const pillars=[{n:'01',icon:Zap,title:'Startup Studio',text:'Move from early validation to a testable MVP with hands-on mentoring and an active incubator network.'},{n:'02',icon:Cpu,title:'Tech Lab',text:'Experiment with AI, IoT, data and design alongside academic and industry partners.'},{n:'03',icon:Users,title:'Community',text:'Meet collaborators at talks, challenges and working sessions built around real problems.'}]
const fade={initial:{opacity:0,y:35},whileInView:{opacity:1,y:0},viewport:{once:true,margin:'-80px'},transition:{duration:.7,ease:[.2,.8,.2,1]}}

function App(){
 const [open,setOpen]=useState(false); const {scrollYProgress}=useScroll(); const scaleX=useSpring(scrollYProgress,{stiffness:90,damping:25})
 useEffect(()=>{const move=e=>{document.documentElement.style.setProperty('--mx',`${e.clientX}px`);document.documentElement.style.setProperty('--my',`${e.clientY}px`)};window.addEventListener('pointermove',move);return()=>window.removeEventListener('pointermove',move)},[])
 const go=id=>{setOpen(false);document.querySelector(id)?.scrollIntoView({behavior:'smooth'})}
 return <><motion.div className="progress" style={{scaleX}}/><div className="noise"/><div className="cursor-glow"/>
  <nav className="nav glass"><button className="brand" onClick={()=>go('#top')}><span className="brand-mark">IX</span><span>INNOVATION<br/>XPERIENCE</span></button><div className={`links ${open?'open':''}`}>{['ABOUT','PROGRAM','EVENTS','CONTACT'].map(x=><button key={x} onClick={()=>go(`#${x.toLowerCase()}`)}>{x}</button>)}<a className="nav-cta" href="#apply">JOIN THE WAVE <ArrowUpRight size={15}/></a></div><button className="menu" aria-label="Menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></nav>
  <main id="top"><section className="hero"><div className="orb o1"/><div className="orb o2"/><div className="grid"/><motion.div className="eyebrow" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.2}}><span/> MAGDEBURG · IDEAS IN MOTION</motion.div><motion.h1 initial={{opacity:0,y:60}} animate={{opacity:1,y:0}} transition={{duration:1,ease:[.16,1,.3,1]}}>INNOVATION<br/><span>XPERIENCE</span></motion.h1><motion.div className="hero-bottom" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.8}}><p>A launchpad for people who want to turn ambitious technology into meaningful, human impact.</p><button className="round" onClick={()=>go('#about')}><ChevronRight/></button></motion.div><div className="marquee"><div>AI · HUMAN-CENTRED DESIGN · IOT · SUSTAINABILITY · RAPID PROTOTYPING · <b>THE NEXT WAVE</b> · AI · HUMAN-CENTRED DESIGN · IOT · SUSTAINABILITY · RAPID PROTOTYPING · </div></div></section>
   <section id="about" className="about section"><motion.div {...fade} className="section-tag">[ 01 — ABOUT ]</motion.div><motion.div {...fade} className="statement"><span>WE CONNECT</span><h2>CURIOUS MINDS, <em>BRAVE IDEAS</em> AND THE TOOLS TO MAKE THEM REAL.</h2></motion.div><div className="about-grid"><motion.div {...fade} className="glass card big"><Sparkles/><p>Innovation Xperience is an open space where students, researchers, founders and industry meet to prototype, validate and build. Less theory alone. More learning by making.</p></motion.div><motion.div {...fade} className="metric"><strong>∞</strong><span>POSSIBILITIES<br/>ONE COMMUNITY</span></motion.div></div></section>
   <section id="program" className="program section"><motion.div {...fade} className="section-head"><div><div className="section-tag">[ 02 — THE EXPERIENCE ]</div><h2>BUILT FOR<br/><i>MOMENTUM.</i></h2></div><p>Three connected spaces. One shared purpose: accelerating ideas that matter.</p></motion.div><div className="pillar-list">{pillars.map(({n,icon:Icon,title,text},i)=><motion.article {...fade} transition={{...fade.transition,delay:i*.08}} key={title}><span>{n}</span><div className="pillar-icon"><Icon/></div><h3>{title}</h3><p>{text}</p><ArrowUpRight className="corner"/></motion.article>)}</div></section>
   <section className="mission"><div className="mission-orb"/><motion.div {...fade}><Globe2/><div className="section-tag">OUR MISSION</div><h2>ACCELERATING<br/>IDEAS THAT <em>MATTER.</em></h2><p>Rapid prototyping. Field validation. Cross-disciplinary collaboration. Designed around people from day one.</p></motion.div></section>
   <section id="events" className="events section"><motion.div {...fade} className="section-head"><div><div className="section-tag">[ 03 — WHAT'S NEXT ]</div><h2>UPCOMING<br/><i>ENERGY.</i></h2></div><p>Dates shown are provisional. Confirmed details and registration links will appear here.</p></motion.div><div className="event-list">{events.map(e=><motion.article {...fade} key={e.title}><div className="date"><strong>{e.day}</strong><span>{e.month}</span></div><span className="event-type">{e.type}</span><h3>{e.title}</h3><button aria-label={`View ${e.title}`}><ArrowUpRight/></button></motion.article>)}</div></section>
   <section id="apply" className="apply section"><motion.div {...fade} className="apply-panel glass"><div><span className="live-dot"/> APPLICATIONS — OPENING SOON</div><h2>YOUR IDEA COULD<br/>BE THE <em>NEXT WAVE.</em></h2><p>Bring the problem worth solving. We’ll help you test the assumptions, meet the right people and build what comes next.</p><a href="mailto:info@innovationxperience.eu?subject=Innovation%20Xperience%20Application">START A CONVERSATION <ArrowUpRight/></a></motion.div></section>
   <section className="partners section"><div className="section-tag">SUPPORTED BY</div><div className="logo-row"><img src="./assets/img/sponsor1.png" alt="Innovation Xperience project partner"/><img src="./assets/img/sponsor2.png" alt="Innovation Xperience funding partner"/><img src="./assets/img/sponsor3.svg" alt="Innovation Xperience institutional partner"/></div></section>
   <section id="contact" className="contact section"><div><div className="section-tag">[ 04 — FIND US ]</div><h2>LET'S MAKE<br/>SOMETHING <i>REAL.</i></h2></div><div className="contact-cards"><a className="glass" href="mailto:info@innovationxperience.eu"><Mail/><span>WRITE TO US</span><strong>info@innovationxperience.eu</strong></a><a className="glass" href="https://maps.google.com/?q=Sandtorstr.+23,+39106+Magdeburg" target="_blank" rel="noreferrer"><MapPin/><span>VISIT THE HUB</span><strong>Experimentelle Fabrik<br/>Sandtorstr. 23 · Magdeburg</strong></a></div></section>
  </main><footer><div className="brand"><span className="brand-mark">IX</span><span>INNOVATION<br/>XPERIENCE</span></div><p>THE NEXT WAVE STARTS HERE.</p><div><a href="mailto:info@innovationxperience.eu">CONTACT</a><a href="https://www.innovationxperience.eu/privacy.html">PRIVACY</a><a href="https://www.innovationxperience.eu/terms.html">TERMS</a></div><small>© {new Date().getFullYear()} Innovation Xperience · Magdeburg</small></footer></>
}
createRoot(document.getElementById('root')).render(<App/>)
