import React,{useState} from 'react'
import{createRoot}from'react-dom/client'
import{motion,useScroll,useSpring}from'framer-motion'
import{ArrowUpRight,ChevronRight,Menu,X,Mail,MapPin,Sparkles,BrainCircuit,Blocks,UsersRound}from'lucide-react'
import'./apple.css'

const team=[
 ['Prof. Dr.-Ing. Ernesto William De Luca','Head, Human-Centred Artificial Intelligence','./images/team/ernesto.jpg','https://ernestodeluca.eu/cv'],
 ['M.Sc. Het Darshan Mehta','PhD Researcher · HCAI, OVGU','./images/team/het.jpeg','https://hetmehta.eu/'],
 ['M.Sc. Iveta Jaroscakova','Innovation Xperience Incubator Coordinator','./images/team/iveta.jpeg','https://www.hcai.ovgu.de/'],
 ['B.Sc. Gavin Rony Correia','HCAI Team','./images/team/gavin.jpeg','https://www.hcai.ovgu.de/'],
 ['B.Sc. Shivnandini Ravikumar Chinnannvar','HCAI Team','./images/team/shivnandini.jpeg','https://www.hcai.ovgu.de/'],
 ['B.Sc. Yashashwini Sidramappa Awate','HCAI Team','./images/team/yashashwini-awate.jpg','https://de.linkedin.com/in/yashashwini-awate-b2abb4227']
]
const events=[['14 OCT','HCAI Leadership Lessons','A leadership series exploring responsible, human-centred AI.'],['24 OCT','Innovation Xperience Kick-off','Meet the community and discover the programme.'],['24—25 NOV','HCAI Symposium','Two days of ideas, research and human-centred technology.']]
const nav=['about','program','events','people','contact','sponsors']
const reveal={initial:{opacity:0,y:32},whileInView:{opacity:1,y:0},viewport:{once:true,margin:'-80px'},transition:{duration:.8,ease:[.16,1,.3,1]}}
const route=name=>`./?view=${name}#${name}`

function Nav(){const[open,setOpen]=useState(false);return <nav className="global-nav"><a href="./" className="ix-logo" aria-label="Innovation Xperience home">Innovation <b>X</b>perience</a><div className={open?'nav-items open':'nav-items'}>{nav.map(item=><a key={item} href={route(item)} target="_blank" rel="noreferrer" onClick={()=>setOpen(false)}>{item}</a>)}</div><button onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></nav>}
function Heading({eyebrow,title,copy}){return <motion.header className="section-title" {...reveal}><span>{eyebrow}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</motion.header>}

function App(){const selected=new URLSearchParams(location.search).get('view')||'home';const{scrollYProgress}=useScroll();const scaleX=useSpring(scrollYProgress,{stiffness:110,damping:25});return <><motion.div className="scrollbar" style={{scaleX}}/><Nav/><main data-view={selected} className={selected==='home'?'home':'focus-view'}>
 <section className="hero"><div className="hero-copy"><motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.15}}>Innovation Xperience · Magdeburg</motion.p><motion.h1 initial={{opacity:0,y:45}} animate={{opacity:1,y:0}} transition={{duration:1,ease:[.16,1,.3,1]}}>Think boldly.<br/><span>Build what matters.</span></motion.h1><motion.div className="hero-links" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.65}}><a href={route('about')} target="_blank">Discover the experience <ChevronRight/></a><a href={route('people')} target="_blank">Meet the team <ChevronRight/></a></motion.div></div><motion.div className="wave-stage" initial={{opacity:0,scale:.92,y:40}} animate={{opacity:1,scale:1,y:0}} transition={{delay:.3,duration:1.2,ease:[.16,1,.3,1]}}><img src="./images/innovation-wave.png" alt="The Innovation Xperience wave"/><div className="stage-label"><span>THE NEXT WAVE</span><b>Ideas in motion.</b></div></motion.div></section>

 <section id="about" className="about page-section"><Heading eyebrow="This is Innovation Xperience" title={<>A place for ideas<br/>with real impact.</>} copy="An open environment where students, researchers, founders and industry partners turn ambition into practical, human-centred innovation."/><div className="feature-grid"><motion.article {...reveal} className="feature-card blue"><span>01</span><h3>Open by design.</h3><p>Different disciplines, perspectives and experiences come together around problems worth solving.</p><div className="orbital"><i/><i/><Sparkles/></div></motion.article><motion.article {...reveal} className="feature-card dark"><span>02</span><h3>Human at the centre.</h3><p>Technology should amplify people—not replace them. Ethics, fairness and usability are part of every build.</p><BrainCircuit/></motion.article><motion.article {...reveal} className="feature-card wide"><span>03</span><h3>From thought to thing.</h3><p>Prototype quickly. Test honestly. Learn continuously.</p><div className="process"><b>IDEA</b><i/><b>PROTOTYPE</b><i/><b>IMPACT</b></div></motion.article></div></section>

 <section id="program" className="program page-section"><Heading eyebrow="The experience" title={<>Everything an idea<br/>needs to move.</>} copy="Three connected environments create the momentum to validate, build and grow."/><div className="program-list">{[[Blocks,'Startup Studio','Shape the problem, validate demand and move toward a testable MVP.'],[BrainCircuit,'Tech Lab','Explore AI, IoT, data and design with academic and industry expertise.'],[UsersRound,'Community','Find collaborators through talks, working sessions and shared challenges.']].map(([Icon,title,text],i)=><motion.article {...reveal} key={title}><span>0{i+1}</span><Icon/><div><h3>{title}</h3><p>{text}</p></div><ArrowUpRight/></motion.article>)}</div><div className="research"><p>HCAI RESEARCH FOCUS</p><div>{['Responsible AI','Ethical AI','Explainability','Bias & Fairness','Human–AI Collaboration','NLP','Usability','Privacy'].map(x=><span key={x}>{x}</span>)}</div></div></section>

 <section id="events" className="events page-section"><Heading eyebrow="On the horizon" title={<>Ideas are better<br/>when shared.</>} copy="Dates remain provisional. Confirmed programme details and registration links will be announced here."/><div className="event-stack">{events.map((e,i)=><motion.article {...reveal} key={e[1]}><time>{e[0]}</time><div><h3>{e[1]}</h3><p>{e[2]}</p></div><span>{String(i+1).padStart(2,'0')}</span></motion.article>)}</div></section>

 <section id="people" className="people page-section"><Heading eyebrow="The people" title={<>Built by curious<br/>minds.</>} copy="Meet the HCAI community behind Innovation Xperience."/><div className="team-grid">{team.map((p,i)=><motion.a {...reveal} href={p[3]} target="_blank" rel="noreferrer" key={p[0]}><img src={p[2]} alt={p[0]} loading="lazy"/><div><span>{String(i+1).padStart(2,'0')}</span><h3>{p[0]}</h3><p>{p[1]}</p></div></motion.a>)}</div></section>

 <section id="contact" className="contact page-section"><div className="contact-panel"><Heading eyebrow="Start something" title={<>Let’s make your<br/>idea real.</>} copy="Talk to us about the problem you want to solve, the team you are building or the support you need."/><div className="contact-actions"><a href="mailto:info@innovationxperience.eu"><Mail/>info@innovationxperience.eu<ArrowUpRight/></a><a href="https://maps.google.com/?q=Sandtorstr.+23,+39106+Magdeburg" target="_blank" rel="noreferrer"><MapPin/>Experimentelle Fabrik · Magdeburg<ArrowUpRight/></a></div></div></section>

 <section id="sponsors" className="sponsors page-section"><Heading eyebrow="Together with" title={<>A network that<br/>makes it possible.</>} copy="Hosted and supported by research, university, innovation and funding partners."/><div className="sponsor-grid"><a href="https://www.hcai.ovgu.de/" target="_blank"><img src="./images/partners/hcai.png" alt="Human-Centred Artificial Intelligence"/></a><a href="https://www.ovgu.de/" target="_blank"><img src="./images/partners/ovgu.png" alt="Otto von Guericke University Magdeburg"/></a><a href="https://www.exfa.de/" target="_blank"><img src="./images/partners/experimentelle-fabrik.png" alt="Experimentelle Fabrik Magdeburg"/></a><a href="https://www.ib-sachsen-anhalt.de/de/" target="_blank"><img src="./images/partners/investitionsbank.png" alt="Investitionsbank Sachsen-Anhalt"/></a></div></section>
 </main><footer><a href="./" className="ix-logo">Innovation <b>X</b>perience</a><p>Human-centred ideas.<br/>Real-world impact.</p><div><a href="mailto:info@innovationxperience.eu">Contact</a><a href="https://www.innovationxperience.eu/privacy.html">Privacy</a><a href="https://www.innovationxperience.eu/terms.html">Terms</a></div><small>© {new Date().getFullYear()} Innovation Xperience · Magdeburg</small></footer></>}
createRoot(document.getElementById('root')).render(<App/> )
